server:
  port: 8082
  servlet:
    context-path: /game-service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

services:
  pgService:
    url:  http://localhost:8089/partner-service
  walletService:
    url: http://localhost:8086/wallet-service


partner:
  pg:
    productId: PGSOFT
    provider:

springdoc:
  swagger-ui:
    path: /swagger-ui.html