server:
  port: 8082
  servlet:
    context-path: /game-service

spring:
  data:
    mongodb:
      host: localhost           # MongoDB server hostname or IP address
      port: 27017               # MongoDB server port
      database: testDb           # Database name
      authentication-database: admin   # Authentication database (optional)
      uri: mongodb://localhost:27017/testDb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_schema: public

services:
  walletService:
    #  url: http://34.132.133.90:8086/wallet-service
    #url: http://34.41.109.236:8086/wallet-service
    url: http://localhost:8086/wallet-service
  memberService:
    #url: http://34.67.253.22:8080/member-service
    url: http://localhost:8080/member-service


partner:
  pg:
    productId: PGSOFT
    provider:

springdoc:
  swagger-ui:
    path: /swagger-ui.html