apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-game-service-deployment
  labels:
    {{- include "helm-chart3.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-chart3.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-chart3.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-chart3.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.container.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
              - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: "8080"
            - name: INSTANCE_CONNECTION_NAME
              value: root
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: root
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: root
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: testing
                  key: database