server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: user
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


services:
  pgService:
    url: https://clients.pglaz.com
  walletService:
    url: http://localhost:8082/wallet-api


partner:
  pg:
    productId: PGSOFT
    provider:
